import {useEffect,useRef} from 'react';
import './request-tracking.css';
const markup="<div class=\"wrap\">\n<section class=\"tracking-hero\">\n<div class=\"intro\"><p class=\"eyebrow\">TALEP TAKİBİ</p><h1>Talep durumunuzu takip edin</h1><p>Talebinizin güncel durumunu, planlanan işlemleri ve ekibimizin yanıtlarını görüntüleyin.</p></div>\n<form id=\"inquiry-status-form\" class=\"query-card\" novalidate>\n<label for=\"status-phone\">Telefon numaranız<div class=\"phone-shell\"><span aria-hidden=\"true\"><svg width=\"19\" height=\"19\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.4 2.1L8.1 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.6 1.9z\"/></svg></span><input id=\"status-phone\" name=\"phone\" type=\"tel\" autocomplete=\"tel\" inputmode=\"tel\" maxlength=\"40\" placeholder=\"05xx xxx xx xx\" aria-describedby=\"phone-help phone-format\" required></div><small id=\"phone-help\">Talep oluştururken kullandığınız numarayı girin.</small></label>\n<p id=\"phone-format\" class=\"phone-format\">Numaranızı <strong>+90</strong>, <strong>0</strong> ile veya doğrudan <strong>5xx</strong> şeklinde yazabilirsiniz.</p>\n<button id=\"status-submit\" type=\"submit\">Talep durumunu sorgula</button>\n</form>\n</section>\n<div id=\"status-message\" class=\"message\" hidden></div>\n<section id=\"status-results\" class=\"results\" aria-live=\"polite\"></section>\n<div class=\"actions\"><a href=\"/iletisim\" class=\"new-support-action\">Yeni destek talebi oluştur <span aria-hidden=\"true\">→</span></a></div>\n<p class=\"privacy\">Bu ekranda yalnızca talep durumunuz ve size iletilen yanıtlar gösterilir. Bilgileriniz gizli tutulur.</p>\n</div>";
export default function RequestTracking(){const ref=useRef(null);useEffect(()=>{const root=ref.current;

const form=root.querySelector('#inquiry-status-form'),input=root.querySelector('#status-phone'),button=root.querySelector('#status-submit'),message=root.querySelector('#status-message'),results=root.querySelector('#status-results');
const normalize=value=>{let d=String(value||'').replace(/\D/g,'');if(d.startsWith('0090')&&d.length===14)d=d.slice(4);else if(d.startsWith('90')&&d.length===12)d=d.slice(2);else if(d.startsWith('0')&&d.length===11)d=d.slice(1);return d;};
const text=(tag,value,cls)=>{const el=document.createElement(tag);if(cls)el.className=cls;el.textContent=value;return el;};
const addMeta=(wrap,label,value)=>{const box=document.createElement('div');box.className='meta';box.append(text('small',label),text('strong',value||'—'));wrap.append(box);};
const render=rows=>{results.replaceChildren();for(const row of rows){const card=document.createElement('article');card.className='result-card';const top=document.createElement('div');top.className='result-top';const left=document.createElement('div');left.append(text('span',row.type,'result-type'),text('strong',row.requestCode,'result-code'));const status=text('span',row.status,'status '+String(row.statusKey||'').toLowerCase());top.append(left,status);const meta=document.createElement('div');meta.className='result-meta';const date=row.created?new Date(row.created).toLocaleString('tr-TR'):'—';addMeta(meta,'Talep tarihi',date);addMeta(meta,'Ürün / konu',row.productName||row.businessName||row.type);addMeta(meta,'Servis planı',row.appointmentDate?new Date(row.appointmentDate+'T00:00:00').toLocaleDateString('tr-TR'):'Henüz planlanmadı');card.append(top,meta);
if(row.callbackAt){const cb=text('div','Planlanan telefon görüşmesi: '+new Date(row.callbackAt).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'}),'result-callback');card.append(cb);}
if(row.publicReply){const rep=document.createElement('div');rep.className='result-reply';rep.append(text('small','İNOKSKAR YANITI'),text('p',row.publicReply));card.append(rep);}
if(Array.isArray(row.replyHistory)&&row.replyHistory.length>1){const history=document.createElement('details');history.className='result-history';history.append(text('summary','Önceki yanıtlar ('+(row.replyHistory.length-1)+')'));for(const item of row.replyHistory.slice(0,-1).reverse()){const article=document.createElement('article');article.append(text('time',item.created?new Date(item.created).toLocaleString('tr-TR'):'—'),text('p',item.text||''));history.append(article);}card.append(history);}
results.append(card);}};
const submit=async e=>{e.preventDefault();message.hidden=true;message.className='message';results.replaceChildren();const normalized=normalize(input.value);if(normalized.length!==10){message.textContent='Geçerli bir Türkiye telefon numarası girin. +90, 0 veya ülke kodu olmadan yazabilirsiniz.';message.className='message error';message.hidden=false;input.focus();return;}button.disabled=true;button.textContent='Sorgulanıyor…';try{const response=await fetch('/api/inquiry-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:input.value})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Talep durumu sorgulanamadı.');if(!body.inquiries?.length){message.textContent='Bu telefon numarasıyla eşleşen bir destek veya servis talebi bulunamadı.';message.className='message error';message.hidden=false;return;}render(body.inquiries);message.textContent=body.inquiries.length+' talep bulundu.';message.hidden=false;}catch(err){message.textContent=err?.message||'Talep durumu sorgulanamadı.';message.className='message error';message.hidden=false;}finally{button.disabled=false;button.textContent='Talep durumunu sorgula';}};
form.addEventListener('submit',submit);
return()=>form.removeEventListener('submit',submit);
},[]);return <div className="request-tracking" ref={ref} dangerouslySetInnerHTML={{__html:markup}}/>;}
