export type Category={id:string,name:string,parent:string,description:string,image:string,menu:boolean,visible:boolean,seoTitle:string,seoDescription:string};
export type Product={id:string,code?:string,name:string,category:string,euro:number,tl:number,vatRate:number,description:string,after:string,specs:{name:string,value:string}[],images:string[],pdf:string,status:string,visible:boolean,demo:boolean,seoTitle:string,seoDescription:string};
export type Reference={id:string,logo:string,phone:string,email:string,visible:boolean};
export type Catalog={references:Reference[],settings:{name:string,tagline:string,heroTitle:string,heroHeading:string,heroAccent:string,heroText:string,hero:string,headerImage:string,founderLabelText:string,founderLabelVisible:boolean,phone:string,whatsapp:string,email:string,notificationEmail:string,address:string,hours:string,social:string,waMessage:string,waEnabled:boolean,rate:number,autoRate:boolean,lastRate:string,rateSource:string,rateDate:string,about:string,menu:{name:string,url:string}[]},categories:Category[],products:Product[]};
export const PRICE_CHANGE_THRESHOLD_TL=500;
export function steppedPrice(raw:number,last?:number){if(!(raw>0))return 0;if(last===undefined||!(last>0))return Math.round(raw);return Math.abs(raw-last)>=PRICE_CHANGE_THRESHOLD_TL?Math.round(raw):last;}
export const seed:Catalog={settings:{name:'İNOKSKAR',tagline:'Soğutma · Mutfak · Mobilya',heroHeading:'Endüstriyel\nMutfaklarda',heroAccent:'Güçlü Partneriniz',heroTitle:'İşinizin gücüne\nyakışan ekipmanlar.',heroText:'Profesyonel çalışma alanları için soğutma, mutfak ve mobilya çözümleri.',hero:'/hero.png',headerImage:'/inokskar-header-brand.png',founderLabelText:'BİR YİĞİTKAR DEKOR KURULUŞUDUR',founderLabelVisible:true,phone:'',whatsapp:'',email:'',notificationEmail:'',address:'',hours:'',social:'',waMessage:'Merhaba, ürünleriniz hakkında bilgi almak istiyorum.',waEnabled:true,rate:0,autoRate:true,lastRate:'',rateSource:'',rateDate:'',about:'Soğutma, endüstriyel mutfak ve ticari mobilyayı bir araya getiren ürün kataloğumuzdan ihtiyacınıza uygun ekipmanları keşfedin.',menu:[{name:'Ürünler',url:'/urunler'},{name:'Hakkımızda',url:'/hakkimizda'},{name:'İletişim',url:'/iletisim'}]},references:[],categories:[{id:'sogutma',name:'Sanayi Soğutma',parent:'',description:'Doğru sıcaklık. Kesintisiz performans.',image:'',menu:true,visible:true,seoTitle:'',seoDescription:''},{id:'mutfak',name:'Endüstriyel Mutfak',parent:'',description:'Üretimin her aşamasına güçlü çözümler.',image:'',menu:true,visible:true,seoTitle:'',seoDescription:''},{id:'mobilya',name:'Ticari Mobilya',parent:'',description:'Çalışma alanınıza sağlam bir temel.',image:'',menu:true,visible:true,seoTitle:'',seoDescription:''},{id:'dolaplar',name:'Soğutma Dolapları',parent:'sogutma',description:'',image:'',menu:false,visible:true,seoTitle:'',seoDescription:''},{id:'pisirme',name:'Pişirme Ekipmanları',parent:'mutfak',description:'',image:'',menu:false,visible:true,seoTitle:'',seoDescription:''},{id:'tezgah',name:'Çalışma Tezgâhları',parent:'mobilya',description:'',image:'',menu:false,visible:true,seoTitle:'',seoDescription:''}],products:[{id:'ornek-dolap',name:'Dik Tip Soğutma Dolabı',category:'dolaplar',euro:0,tl:0,vatRate:20,description:'Profesyonel mutfaklarda düzenli ve erişilebilir soğuk depolama için örnek ürün kaydı.',after:'Ölçü ve kapasite bilgileri gerçek ürününüzle birlikte güncellenebilir.',specs:[],images:[],pdf:'',status:'Bilgi alınız',visible:true,demo:true,seoTitle:'',seoDescription:''},{id:'ornek-ocak',name:'Endüstriyel Pişirme Ünitesi',category:'pisirme',euro:0,tl:0,vatRate:20,description:'Yoğun mutfak operasyonlarına yönelik örnek ürün kaydı.',after:'',specs:[],images:[],pdf:'',status:'Sipariş üzerine',visible:true,demo:true,seoTitle:'',seoDescription:''},{id:'ornek-tezgah',name:'Paslanmaz Çalışma Tezgâhı',category:'tezgah',euro:0,tl:0,vatRate:20,description:'Profesyonel hazırlık alanları için örnek ürün kaydı.',after:'',specs:[],images:[],pdf:'',status:'Bilgi alınız',visible:true,demo:true,seoTitle:'',seoDescription:''}]};
const num=(value:unknown,fallback=0)=>{const n=Number(value);return Number.isFinite(n)&&n>=0?n:fallback;};
const str=(value:unknown,fallback='')=>typeof value==='string'?value:fallback;
export function normalizeCatalog(input:any):Catalog{
 const raw=input&&typeof input==='object'?input:{};
 const rs=raw.settings&&typeof raw.settings==='object'?raw.settings:{};
 const settings={...seed.settings,...rs,
  name:str(rs.name,seed.settings.name),tagline:str(rs.tagline,seed.settings.tagline),heroTitle:str(rs.heroTitle,seed.settings.heroTitle),heroHeading:str(rs.heroHeading,seed.settings.heroHeading),heroAccent:str(rs.heroAccent,seed.settings.heroAccent),heroText:str(rs.heroText,seed.settings.heroText),hero:str(rs.hero,seed.settings.hero),headerImage:str(rs.headerImage,seed.settings.headerImage),founderLabelText:str(rs.founderLabelText,seed.settings.founderLabelText),founderLabelVisible:rs.founderLabelVisible!==false,phone:str(rs.phone),whatsapp:str(rs.whatsapp),email:str(rs.email),notificationEmail:str(rs.notificationEmail),address:str(rs.address),hours:str(rs.hours),social:str(rs.social),waMessage:str(rs.waMessage,seed.settings.waMessage),waEnabled:rs.waEnabled!==false,rate:num(rs.rate),autoRate:rs.autoRate!==false,lastRate:str(rs.lastRate),rateSource:str(rs.rateSource),rateDate:str(rs.rateDate),about:str(rs.about,seed.settings.about),menu:Array.isArray(rs.menu)?rs.menu.filter((m:any)=>m&&typeof m==='object'&&m.url!=='/blog').map((m:any)=>({name:str(m.name),url:str(m.url)})):seed.settings.menu
 };
 const categories=(Array.isArray(raw.categories)?raw.categories:[]).map((c:any)=>({id:str(c?.id),name:str(c?.name),parent:str(c?.parent),description:str(c?.description),image:str(c?.image),menu:c?.menu===true,visible:c?.visible!==false,seoTitle:str(c?.seoTitle),seoDescription:str(c?.seoDescription)})).filter((c:Category)=>c.id&&c.name);
 const products=(Array.isArray(raw.products)?raw.products:[]).map((p:any)=>({
  id:str(p?.id),code:str(p?.code),name:str(p?.name),category:str(p?.category),euro:num(p?.euro),tl:num(p?.tl),vatRate:Math.min(100,num(p?.vatRate,20)),description:str(p?.description),after:str(p?.after),
  specs:Array.isArray(p?.specs)?p.specs.filter((x:any)=>x&&typeof x==='object').map((x:any)=>({name:str(x.name),value:str(x.value)})):[],
  images:Array.isArray(p?.images)?p.images.filter((x:any)=>typeof x==='string'&&x.trim()).map((x:string)=>x.trim()):[],pdf:str(p?.pdf),status:['Stokta','Sipariş üzerine','Bilgi alınız'].includes(str(p?.status))?str(p.status):'Bilgi alınız',visible:p?.visible!==false,demo:p?.demo===true,seoTitle:str(p?.seoTitle),seoDescription:str(p?.seoDescription)
 })).filter((p:Product)=>p.id&&p.name&&p.category);
 const references=(Array.isArray(raw.references)?raw.references:[]).map((r:any)=>({id:str(r?.id),logo:str(r?.logo),phone:str(r?.phone),email:str(r?.email),visible:r?.visible!==false})).filter((r:Reference)=>r.id&&r.logo);
 return {settings,categories,products,references};
}
export function descendants(categories:Category[],id:string):string[]{const ids=[id];for(let i=0;i<ids.length;i++)for(const c of categories)if(c.parent===ids[i]&&!ids.includes(c.id))ids.push(c.id);return ids;}
export function publicCategories(categories:Category[]){return categories.filter(c=>{let node:Category|undefined=c;const seen=new Set<string>();while(node){if(!node.visible||seen.has(node.id))return false;seen.add(node.id);if(!node.parent)return true;node=categories.find(x=>x.id===node!.parent);}return false;});}
export function safeLink(value:string){if(typeof value!=='string'||/[\\\u0000-\u0020]/.test(value))return false;if(!/^\/(?!\/)/.test(value)&&!/^https?:\/\//i.test(value))return false;try{const url=new URL(value,'https://site.invalid');return ['http:','https:'].includes(url.protocol)&&!!url.hostname;}catch{return false;}}
export const productCode=(p:Pick<Product,'id'|'code'>)=>p.code?.trim()||p.id;
export const matchesProductCode=(p:Product,query:string)=>!!query.trim()&&productCode(p).toLowerCase().includes(query.trim().toLowerCase());
export const matchesProduct=(p:Product,query:string)=>p.name.toLocaleLowerCase('tr').includes(query.trim().toLocaleLowerCase('tr'))||matchesProductCode(p,query);
